version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=igcallpg
      - POSTGRESQL_PASSWORD=igcallpg
      - POSTGRESQL_DATABASE=ignitecall